runtime: nodejs
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "18"
env: flex
entrypoint: node app.js
env_variables:
  APP_ID: "1086030679881568316"
  GUILD_ID: "1059264631618666506"
  DISCORD_TOKEN: "MTA4NjAzMDY3OTg4MTU2ODMxNg.GnL9_-.C5ZazC7aId5Awu_OJ4rqx3DZrsqM67UOh0gTNI"
  PUBLIC_KEY: "f3123f34ecc1b71cb3a5ee015f543ef5a4228978989d81051f55c7c223de7b2b"
network:
  forwarded_ports:
    - 3000/tcp
